name: check for down machines

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x check.sh

      - name: Run script
        run: ./check.sh
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update status.json"
